# Generated by Django 5.1.4 on 2026-07-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='easy_mode',
            field=models.BooleanField(default=True),
        ),
    ]
