# Generated by Django 5.1.4 on 2026-08-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_easy_mode_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
