# Generated by Django 5.1.4 on 2026-09-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_onboarded'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyModeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('mode', models.CharField(max_length=4)),
            ],
            options={
                'unique_together': {('session_key', 'date')},
            },
        ),
    ]
