# Generated by Django 5.1.4 on 2026-09-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_dailymodesession_hash_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_tour_seen',
            field=models.BooleanField(default=False),
        ),
    ]
