# Generated by Django 5.1.4 on 2026-09-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_onboarding_tour_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('aborted', 'Aborted')], max_length=10)),
                ('mode', models.CharField(max_length=4)),
                ('source', models.CharField(blank=True, choices=[('welcome', 'Welcome dialog'), ('help', 'Help menu')], max_length=10)),
                ('step', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
