# Generated by Django 5.1.4 on 2026-09-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_onboarding_tour_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDailyCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('kind', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('aborted', 'Aborted')], max_length=10)),
                ('mode', models.CharField(max_length=4)),
                ('source', models.CharField(blank=True, choices=[('welcome', 'Welcome dialog'), ('help', 'Help menu')], max_length=10)),
                ('step', models.CharField(blank=True, max_length=60)),
                ('n', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'kind', 'mode', 'source', 'step'), name='one_tour_count_per_bucket')],
            },
        ),
    ]
