# Generated by Django 5.1.4 on 2026-07-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='open_on_show',
            field=models.BooleanField(default=False),
        ),
    ]
