# Generated by Django 5.1.4 on 2026-07-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_questionset_open_on_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionset',
            name='show_results_to_participants',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('word_cloud', 'Word cloud'), ('likert', 'Likert scale'), ('open_text', 'Open text')], max_length=20),
        ),
    ]
