# Generated by Django 5.1.4 on 2026-07-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_question_time_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='is_abstention',
            field=models.BooleanField(default=False),
        ),
    ]
