# Generated by Django 5.1.4 on 2026-07-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_answeroption_is_abstention'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='license',
            field=models.CharField(blank=True, choices=[('cc0', 'CC0 (public domain)'), ('cc-by', 'CC BY 4.0'), ('cc-by-sa', 'CC BY-SA 4.0'), ('cc-by-nc', 'CC BY-NC 4.0'), ('cc-by-nc-sa', 'CC BY-NC-SA 4.0')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='questionset',
            name='share_token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
