# Generated by Django 5.1.4 on 2026-07-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_questionset_license_questionset_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='image',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
