# Generated by Django 5.1.4 on 2026-07-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_room_created_by_room_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(editable=False, max_length=60, unique=True),
        ),
    ]
