# Generated by Django 5.1.4 on 2026-07-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='license_holder',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='license',
            field=models.CharField(blank=True, choices=[('cc0', 'CC0 (public domain)'), ('cc-by', 'CC BY 4.0'), ('cc-by-sa', 'CC BY-SA 4.0'), ('cc-by-nc', 'CC BY-NC 4.0'), ('cc-by-nc-sa', 'CC BY-NC-SA 4.0'), ('copyright', '© All rights reserved')], default='', max_length=20),
        ),
    ]
