# Generated by Django 5.1.4 on 2026-07-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='show_logo_in_presentation',
            field=models.BooleanField(default=True),
        ),
    ]
