# Generated by Django 5.1.4 on 2026-07-08 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_merge_20260708_0813'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
