# Generated by Django 5.1.4 on 2026-07-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_question_ai_evaluate_question_evaluation_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='presentation_corner',
            field=models.CharField(choices=[('top-left', 'oben links'), ('top-right', 'oben rechts'), ('bottom-left', 'unten links'), ('bottom-right', 'unten rechts')], default='bottom-right', max_length=12),
        ),
        migrations.AddField(
            model_name='room',
            name='show_code_in_presentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='show_qr_in_presentation',
            field=models.BooleanField(default=False),
        ),
    ]
