# Generated by Django 5.1.4 on 2026-07-09 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_room_presentation_corner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='archived_by',
            field=models.ManyToManyField(blank=True, related_name='archived_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
