# Generated by Django 5.1.4 on 2026-07-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_room_archived_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_multiple',
            field=models.BooleanField(default=False),
        ),
    ]
