# Generated by Django 5.1.4 on 2026-07-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_question_allow_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='wordcloud_live',
            field=models.BooleanField(default=True),
        ),
    ]
