# Generated by Django 5.1.4 on 2026-07-09 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owner(apps, schema_editor):
    """Existing rooms adopt their creator as Besitzer, falling back to the
    earliest co-owner (dev rooms may have no created_by)."""
    Room = apps.get_model("rooms", "Room")
    for room in Room.objects.all():
        owner = room.created_by
        if owner is None or not room.owners.filter(pk=owner.pk).exists():
            owner = room.owners.order_by("pk").first()
        if owner is not None:
            room.owner = owner
            room.save(update_fields=["owner"])


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0017_question_wordcloud_live'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_owner, migrations.RunPython.noop),
    ]
