# Generated by Django 5.1.4 on 2026-07-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reveal_answers',
            field=models.CharField(choices=[('inherit', 'Wie im Set'), ('immediately', 'Immediately with the results'), ('after_close', 'After closing, on reveal'), ('never', 'Never')], default='inherit', max_length=20),
        ),
    ]
