# Generated by Django 5.1.4 on 2026-07-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_question_reveal_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='closing_info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
