# Generated by Django 5.1.4 on 2026-07-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0020_room_closing_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='wordcloud_grouping',
            field=models.TextField(blank=True),
        ),
    ]
