# Generated by Django 5.1.4 on 2026-07-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0021_question_wordcloud_grouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='wordcloud_ai_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
