# Generated by Django 5.1.4 on 2026-07-14 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0027_backfill_owner_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='before_question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='after_question', to='rooms.question'),
        ),
    ]
