# Generated by Django 5.1.4 on 2026-07-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0029_alter_question_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('word_cloud', 'Word cloud'), ('likert', 'Likert scale'), ('open_text', 'Open text'), ('priorities', 'Priorities'), ('ordering', 'Ordering')], max_length=20),
        ),
    ]
