# Generated by Django 5.1.4 on 2026-07-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0030_alter_question_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='wordcloud_max_answers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
