# Generated by Django 5.1.4 on 2026-08-12 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0031_question_wordcloud_max_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('word_cloud', 'Word cloud'), ('likert', 'Likert scale'), ('open_text', 'Open text'), ('priorities', 'Priorities'), ('ordering', 'Ordering'), ('matrix', 'Matrix')], max_length=20),
        ),
        migrations.CreateModel(
            name='MatrixColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('text_en', models.CharField(blank=True, max_length=200, null=True)),
                ('text_de', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='rooms.question')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
