# Generated by Django 5.1.4 on 2026-08-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0031_question_wordcloud_max_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='binary_choice',
            field=models.BooleanField(default=False),
        ),
    ]
