# Generated by Django 5.1.4 on 2026-08-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0032_question_binary_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='model_solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='participant_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
