# Generated by Django 5.1.4 on 2026-08-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0033_question_model_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='open_on_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='reveal_answers',
            field=models.CharField(choices=[('immediately', 'Immediately with the results'), ('after_close', 'After closing, on key press'), ('never', 'Never')], default='immediately', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='show_results_to_participants',
            field=models.BooleanField(default=True),
        ),
    ]
