# Generated by Django 5.1.4 on 2026-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0034_alter_questionset_open_on_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='translation_sync',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
