# Generated by Django 5.1.4 on 2026-08-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0035_question_translation_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='type',
            field=models.CharField(choices=[('live_poll', 'Live poll'), ('self_paced', 'Self-paced quiz'), ('self_check', 'Self-check')], default='live_poll', max_length=20),
        ),
    ]
