# Generated by Django 5.1.4 on 2026-08-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0036_questionset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='quiz_time_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
