# Generated by Django 5.1.4 on 2026-08-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0038_questionset_present_results_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='allow_back_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionset',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
    ]
