# Generated by Django 5.1.4 on 2026-09-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0039_questionset_allow_back_navigation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='self_check_token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
