# Generated by Django 5.1.4 on 2026-09-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0040_questionset_self_check_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='reveal_only_in_summary',
            field=models.BooleanField(default=False),
        ),
    ]
