# Generated by Django 5.1.4 on 2026-09-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0041_questionset_reveal_only_in_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='wordcloud_batch_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='wordcloud_max_answers',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
