# Generated by Django 5.1.4 on 2026-09-15 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0044_likert_reverse_scale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('kinds', models.JSONField(blank=True, default=list)),
                ('level', models.CharField(default='mixed', max_length=16)),
                ('guidance', models.TextField(blank=True)),
                ('source_text', models.TextField()),
                ('total_chunks', models.PositiveIntegerField(default=0)),
                ('done_chunks', models.PositiveIntegerField(default=0)),
                ('drafts', models.JSONField(blank=True, default=list)),
                ('truncated', models.BooleanField(default=False)),
                ('source_chars', models.PositiveIntegerField(default=0)),
                ('notice', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='rooms.questionset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
