# Generated by Django 5.1.4 on 2026-09-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0045_generationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='density',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='target_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
