# Generated by Django 5.1.4 on 2026-09-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0046_generationjob_density_generationjob_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='focus_kinds',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
