# Generated by Django 5.1.4 on 2026-09-24 05:36

from django.db import migrations, models


def backfill(apps, schema_editor):
    Room = apps.get_model("rooms", "Room")
    Room.objects.filter(title_de="Beispielraum – zum Ausprobieren").update(is_example=True)


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0047_generationjob_focus_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_example',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
