# Generated by Django 5.1.4 on 2026-10-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0048_room_is_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='wordcloud_merge_concepts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='wordcloud_merge_synonyms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='wordcloud_merge_variants',
            field=models.BooleanField(default=True),
        ),
    ]
