# Generated by Django 5.1.4 on 2026-10-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0049_wordcloud_merge_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='wordcloud_grouping_use_solution',
            field=models.BooleanField(default=True),
        ),
    ]
