# Generated by Django 5.1.4 on 2026-10-07 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0050_grouping_use_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mindmap_depth',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='question',
            name='mindmap_descriptions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='mindmap_highlight_duplicates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='mindmap_max_per_person',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='question',
            name='mindmap_root',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='question',
            name='mindmap_root_de',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='mindmap_root_en',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='mindmap_seed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('word_cloud', 'Word cloud'), ('likert', 'Likert scale'), ('open_text', 'Open text'), ('priorities', 'Priorities'), ('ordering', 'Ordering'), ('mindmap', 'Mindmap')], max_length=20),
        ),
    ]
