# Generated by Django 5.1.4 on 2026-10-08 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0052_mindmap_seed_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mindmap_rating_budget',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='question',
            name='mindmap_rating_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='mindmap_rating_mode',
            field=models.CharField(blank=True, choices=[('', 'Off'), ('points', 'Points'), ('updown', 'Plus/minus')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='mindmap_rating_multi',
            field=models.BooleanField(default=True),
        ),
    ]
