# Generated by Django 5.1.4 on 2026-07-06 21:10

import django.db.models.deletion
import live.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=live.models.generate_token_key, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(choices=[('lobby', 'Lobby'), ('preview', 'Question shown, not yet open'), ('open', 'Accepting votes'), ('closed', 'Voting closed'), ('results', 'Results on the beamer'), ('finished', 'Finished')], default='lobby', max_length=10)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rooms.question')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='rooms.questionset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=60)),
                ('text_key', models.CharField(blank=True, db_index=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('options', models.ManyToManyField(blank=True, related_name='votes', to='rooms.answeroption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='rooms.question')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='live.run')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='live.participanttoken')),
            ],
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.UniqueConstraint(condition=models.Q(('phase', 'finished'), _negated=True), fields=('question_set',), name='one_active_run_per_set'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('run', 'question', 'token'), name='one_vote_per_token'),
        ),
    ]
