# Generated by Django 5.1.4 on 2026-07-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='answers_revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='run',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
