# Generated by Django 5.1.4 on 2026-07-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_run_answers_revealed_run_opened_at_alter_vote_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='mode',
            field=models.CharField(choices=[('live', 'Teacher-paced (live)'), ('self_paced', 'Self-paced quiz')], default='live', max_length=10),
        ),
    ]
