# Generated by Django 5.1.4 on 2026-07-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_run_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='ai_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vote',
            name='ai_verdict',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
