# Generated by Django 5.1.4 on 2026-07-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_vote_ai_note_vote_ai_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='first_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
