# Generated by Django 5.1.4 on 2026-07-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0005_run_first_opened_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='one_vote_per_token',
        ),
    ]
