# Generated by Django 5.1.4 on 2026-07-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0006_remove_vote_one_vote_per_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='ai_verdict',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
