# Generated by Django 5.1.4 on 2026-07-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0007_alter_vote_ai_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='recording_token',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='source',
            field=models.CharField(choices=[('onsite', 'On-site (live)'), ('recording', 'Recording viewer (async, #53)')], default='onsite', max_length=10),
        ),
    ]
