# Generated by Django 5.1.4 on 2026-07-16 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0008_run_recording_token_vote_source'),
        ('rooms', '0029_alter_question_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_scores', to='rooms.answeroption')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_scores', to='live.vote')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vote', 'option'), name='one_score_per_vote_option')],
            },
        ),
    ]
