# Generated by Django 5.1.4 on 2026-07-23 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0009_priorityscore'),
        ('rooms', '0030_alter_question_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_responses', to='rooms.answeroption')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_responses', to='live.vote')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vote', 'option'), name='one_ordering_per_vote_option')],
            },
        ),
    ]
