# Generated by Django 5.1.4 on 2026-08-12 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0010_orderingresponse'),
        ('rooms', '0032_alter_question_kind_matrixcolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_responses', to='rooms.matrixcolumn')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_responses', to='rooms.answeroption')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_responses', to='live.vote')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vote', 'row', 'column'), name='one_cell_per_vote')],
            },
        ),
    ]
