# Generated by Django 5.1.4 on 2026-08-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0010_orderingresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='quiz_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
