# Generated by Django 5.1.4 on 2026-09-09 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0011_run_quiz_ends_at'),
        ('rooms', '0040_questionset_self_check_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfCheckAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('scored', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rooms.question')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_check_attempts', to='rooms.questionset')),
            ],
        ),
    ]
