# Generated by Django 5.1.4 on 2026-09-11 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0012_selfcheckattempt'),
        ('rooms', '0044_likert_reverse_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCloudModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hidden', models.JSONField(blank=True, default=list)),
                ('merges', models.JSONField(blank=True, default=list)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.question')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wc_moderations', to='live.run')),
            ],
            options={
                'unique_together': {('run', 'question')},
            },
        ),
    ]
