# Generated by Django 5.1.4 on 2026-10-07 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0013_wordcloudmoderation'),
        ('rooms', '0051_mindmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindmapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
                ('text_key', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('seeded', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='live.mindmapnode')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindmap_nodes', to='rooms.question')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindmap_nodes', to='live.run')),
            ],
        ),
        migrations.CreateModel(
            name='MindmapContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindmap_contributions', to='live.participanttoken')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='live.mindmapnode')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mindmapnode',
            constraint=models.UniqueConstraint(fields=('run', 'question', 'parent', 'text_key'), name='one_mindmap_node_per_parent_key', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='mindmapcontribution',
            constraint=models.UniqueConstraint(fields=('node', 'token'), name='one_mindmap_contribution_per_token'),
        ),
    ]
