# Generated by Django 5.1.4 on 2026-10-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0014_mindmap_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmapnode',
            name='seed_i18n',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
