# Generated by Django 5.1.4 on 2026-10-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0015_mindmap_seed_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmapnode',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
    ]
