# Generated by Django 5.1.4 on 2026-10-08 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0016_mindmap_teacher_nodes'),
        ('rooms', '0053_mindmap_rating_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindmapPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('collect', 'Collecting terms'), ('rate', 'Rating the entries')], default='collect', max_length=10)),
                ('rating_started_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rooms.question')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindmap_phases', to='live.run')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'question'), name='one_mindmap_phase_per_run_question')],
            },
        ),
        migrations.CreateModel(
            name='MindmapRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='live.mindmapnode')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindmap_ratings', to='live.participanttoken')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('node', 'token'), name='one_mindmap_rating_per_token')],
            },
        ),
    ]
