# Generated by Django 5.1.4 on 2026-07-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_seed_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='closing_info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
