# Generated by Django 5.1.4 on 2026-08-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_markdown_to_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='ai_notice',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ai_notice_de',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ai_notice_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ai_notice_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
