# Generated by Django 5.1.4 on 2026-08-21 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_siteconfig_ai_notice_siteconfig_ai_notice_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='ai_notice_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.page'),
        ),
    ]
