# Generated by Django 5.1.4 on 2026-09-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_siteconfig_ai_notice_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='self_check_ai_per_minute',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
