# Generated by Django 5.1.4 on 2026-09-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_siteconfig_self_check_ai_per_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='beta_label_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='beta_notice',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='beta_notice_de',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='beta_notice_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
