# Generated by Django 5.1.4 on 2026-07-07 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtiToolKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LtiPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Anzeigename, z. B. „Moodle Uni OS“', max_length=200)),
                ('issuer', models.CharField(max_length=500)),
                ('client_id', models.CharField(max_length=255)),
                ('auth_login_url', models.URLField(max_length=500)),
                ('auth_token_url', models.URLField(max_length=500)),
                ('key_set_url', models.URLField(blank=True, max_length=500)),
                ('key_set', models.JSONField(blank=True, null=True)),
                ('deployment_ids', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('issuer', 'client_id'), name='unique_platform_registration')],
            },
        ),
        migrations.CreateModel(
            name='LtiContextLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_id', models.CharField(max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lti_links', to='rooms.room')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_links', to='lti.ltiplatform')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('platform', 'context_id'), name='one_room_per_context')],
            },
        ),
    ]
