# Generated by Django 5.1.4 on 2026-07-07 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiplatform',
            name='link_by_email',
            field=models.BooleanField(default=False, help_text='Beim ersten Launch unbekannte LTI-Nutzer über die E-Mail-Adresse mit bestehenden Konten verknüpfen (nur für vertrauenswürdige Plattformen aktivieren).'),
        ),
        migrations.CreateModel(
            name='LtiUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub', models.CharField(max_length=255)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='lti.ltiplatform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lti_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('platform', 'sub'), name='one_user_per_lti_subject')],
            },
        ),
    ]
